# Logistic Regression
- data : load_breast_cancer
- evaluation : acc, confusion matrix

In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

## Data Load


In [52]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [53]:
data = cancer.data
label = cancer.target
columns = cancer.feature_names

In [54]:
data = pd.DataFrame(data, columns=columns)
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [55]:
data.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst radius  \
count     569.000000              569.000000  ...    569.000000   
mean        0.181162                0.062798  ...     16.269190   
std         0.027414                0.007060  ...      4.833242   
min         0.106000                0.049960  ...      7.930000   
25%         0.161900                0.057700  ...     13.010000   
50%         0.179200                0.061540  ...     14.970000   
75%         0.195700                0.066120  ...     18.790000   
max         0.304000                0.097440  ...     36.040000   

       worst texture  worst perimeter   worst area  worst smoothness  \
count     569.000000       569.000000   569.000000        569.000000   
mean       25.677223       107.261213   880.583128          0.132369   
std         6.146258        33.602542   569.356993          0.022832   
min        12.020000        50.410000   185.200000          0.071170   
25%        21.080000        84.110000   515.300000          0.116600   
50%        25.410000        97.660000   686.500000          0.131300   
75%        29.720000       125.400000  1084.000000          0.146000   
max        49.540000       251.200000  4254.000000          0.222600   

       worst compactness  worst concavity  worst concave points  \
count         569.000000       569.000000            569.000000   
mean            0.254265         0.272188              0.114606   
std             0.157336         0.208624              0.065732   
min             0.027290         0.000000              0.000000   
25%             0.147200         0.114500              0.064930   
50%             0.211900         0.226700              0.099930   
75%             0.339100         0.382900              0.161400   
max             1.058000         1.252000              0.291000   

       worst symmetry  worst fractal dimension  
count      569.000000               569.000000  
mean         0.290076                 0.083946  
std          0.061867                 0.018061  
min          0.156500                 0.055040  
25%          0.250400                 0.071460  
50%          0.282200                 0.080040  
75%          0.317900                 0.092080  
max          0.663800                 0.207500  

[8 rows x 30 columns]

In [56]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [57]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data, label, test_size=0.2, shuffle=True, stratify=label, random_state=2019)

In [58]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(
    penalty='l1',
    C=0.1,
    class_weight='balanced',
    random_state=1,
    solver='liblinear')

In [59]:
lr.fit(x_train, y_train)

/Users/johanjun/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LogisticRegression(C=0.1, class_weight='balanced', penalty='l1', random_state=1,
                   solver='liblinear')

In [60]:
print("로지스틱 회귀, 계수(w) : {}, 절편(b) : {}".format(lr.coef_, lr.intercept_))

로지스틱 회귀, 계수(w) : [[ 0.          0.          0.37068264 -0.00668328  0.          0.
   0.          0.          0.          0.          0.          0.
   0.         -0.05302746  0.          0.          0.          0.
   0.          0.          0.64819138 -0.12754576 -0.18547585 -0.01973352
   0.          0.          0.          0.          0.          0.        ]], 절편(b) : [0.]


In [61]:
y_pred = lr.predict(x_test)

In [62]:
print(y_pred[:5])

[1 1 1 0 1]


In [63]:
print(lr.predict_proba(x_test)[:5])

[[1.58751980e-02 9.84124802e-01]
 [1.05993340e-01 8.94006660e-01]
 [8.75471058e-02 9.12452894e-01]
 [9.99999732e-01 2.67668159e-07]
 [2.70060924e-03 9.97299391e-01]]


In [64]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, roc_auc_score
print("acc:{:.4f}".format(accuracy_score(y_test, y_pred)))
print("rec:{:.4f}".format(recall_score(y_test, y_pred)))
print("pre:{:.4f}".format(precision_score(y_test, y_pred)))
print("f1:{:.4f}".format(f1_score(y_test, y_pred)))
print("roc:{:.4f}".format(roc_auc_score(y_test, y_pred)))

acc:0.9474
rec:0.9583
pre:0.9583
f1:0.9583
roc:0.9435


In [65]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        42
           1       0.96      0.96      0.96        72

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114



### iris data(multinomial)

In [66]:
from sklearn.datasets import load_iris

In [67]:
iris = load_iris()

data = iris.data
label = iris.target
columns = iris.feature_names

In [68]:
df = pd.DataFrame(data, columns=columns)

In [69]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [70]:
df.shape

(150, 4)

In [71]:
x_train, x_test, y_train, y_test = train_test_split(data, label, stratify=label, shuffle=True, test_size=0.2)

In [72]:
lr = LogisticRegression(multi_class='ovr')

In [73]:
lr.fit(x_train, y_train)

LogisticRegression(multi_class='ovr')

In [74]:
print("로지스틱 회귀, 계수(w) : {}, 절편(b) : {}".format(lr.coef_, lr.intercept_))

로지스틱 회귀, 계수(w) : [[-0.40631891  0.87722048 -2.20498517 -0.91843236]
 [ 0.14886794 -2.18327712  0.47517492 -1.14942985]
 [-0.48949667 -0.42978626  2.7510641   2.19866888]], 절편(b) : [  6.19270785   4.54038155 -12.8238642 ]


In [75]:
y_pred = lr.predict(x_test)

In [76]:
x_test[:5]

array([[5.5, 2.5, 4. , 1.3],
       [5. , 3.6, 1.4, 0.2],
       [6.5, 3. , 5.2, 2. ],
       [5.4, 3.4, 1.7, 0.2],
       [6.3, 3.3, 4.7, 1.6]])

In [77]:
y_pred[:5]

array([1, 0, 2, 0, 2])

In [78]:
y_test[:5]

array([1, 0, 2, 0, 1])

In [79]:
lr.predict_proba(x_test)[:5]

array([[3.12608736e-02, 8.75541918e-01, 9.31972088e-02],
       [9.03230533e-01, 9.67661343e-02, 3.33233732e-06],
       [7.35322191e-04, 2.68568413e-01, 7.30696265e-01],
       [8.39678967e-01, 1.60314511e-01, 6.52218106e-06],
       [9.74048730e-03, 4.11553101e-01, 5.78706412e-01]])

In [83]:
print(accuracy_score(y_test, y_pred))
print(recall_score(y_test, y_pred, average=None))
print(precision_score(y_test, y_pred, average=None))
print(f1_score(y_test, y_pred, average=None))
# print(roc_auc_score(y_test, y_pred, average=None))

0.9666666666666667
[1.  0.9 1. ]
[1.         1.         0.90909091]
[1.         0.94736842 0.95238095]


In [84]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [85]:
lr2 = LogisticRegression(multi_class='multinomial')

In [86]:
lr2.fit(x_train, y_train)

/Users/johanjun/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

In [87]:
y_pred = lr2.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [88]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [89]:
print(accuracy_score(y_test, y_pred))
print(recall_score(y_test, y_pred, average=None))
print(precision_score(y_test, y_pred, average=None))
print(f1_score(y_test, y_pred, average=None))

1.0
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
